Loot Generation
schiltz3/The-DMs-Toolkit pull request #106
Opened 2022-10-13 03:41 UTC by RonenLoundy

2022-10-13 04:10 UTC, RonenLoundy commented
Going to work on some tests to see if it actually works

2022-10-14 01:07 UTC, johnrtabor approved these changes
Looks good to me!

2022-10-14 02:46 UTC, schiltz3 requested changes

2022-10-14 19:31 UTC, JefferyMeverden approved these changes

2022-10-14 20:05 UTC, JefferyMeverden approved these changes

2022-10-14 20:06 UTC, johnrtabor approved these changes

2022-10-14 20:06 UTC, merged